<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UniEvent</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"></head><body>
<header><a href="/" class="brand"><b>U</b><span>UniEvent<small>Smart Campus Events</small></span></a><form method="get"><input name="q" value="{{ request('q') }}" placeholder="Search events or venues"><button>Search</button></form><nav>@auth <span>{{ auth()->user()->name }} ({{ auth()->user()->role }})</span><form method="post" action="{{ route('logout') }}">@csrf<button>Logout</button></form>@else <span>Guest mode</span>@endauth</nav></header>
<section class="hero"><div><small>LARAVEL 13 + NODE.JS</small><h1>Campus events,<br><em>made effortless.</em></h1><p>Discover events, reserve your seat and receive important announcements instantly.</p></div><aside><small>LIVE ANNOUNCEMENT</small><h3 id="live-message">{{ $latestAnnouncement?->message ?? 'The notification server is ready for a live announcement.' }}</h3><p id="connection">Connecting to Socket.IO…</p></aside></section>
<main>
@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
@guest<section class="auth"><form method="post" action="{{ route('login') }}">@csrf<h2>Log in</h2><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button>Log in</button><small>Admin: admin@unievent.test / admin123</small></form><form method="post" action="{{ route('register') }}">@csrf<h2>Create student account</h2><input name="name" placeholder="Full name" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><input name="password_confirmation" type="password" placeholder="Confirm password" required><button>Register</button></form></section>@endguest
<section class="events"><div class="title"><small>DISCOVER</small><h2>Upcoming events</h2></div><div class="grid">@forelse($events as $event)<article><span class="tag">{{ $event->category }}</span><time>{{ $event->event_date->format('d M') }}</time><h3>{{ $event->title }}</h3><p>◷ {{ date('h:i A',strtotime($event->event_time)) }}<br>⌖ {{ $event->venue }}</p><div class="capacity"><span>{{ $event->registrations_count }} registered</span><span>{{ $event->capacity }} seats</span></div>@auth<form method="post" action="{{ route('events.register',$event) }}">@csrf<button>Register now →</button></form>@else<small>Log in to register.</small>@endauth</article>@empty<p>No events found.</p>@endforelse</div></section>
@auth @if(auth()->user()->isAdmin())<section class="admin"><h2>Administrator control</h2><div><form method="post" action="{{ route('admin.events.store') }}">@csrf<h3>Create event</h3><input name="title" placeholder="Title" required><input name="category" placeholder="Category" required><input name="event_date" type="date" required><input name="event_time" type="time" required><input name="venue" placeholder="Venue" required><input name="capacity" type="number" placeholder="Capacity" required><textarea name="description" placeholder="Description"></textarea><button>Create event</button></form><form method="post" action="{{ route('admin.announcements.store') }}">@csrf<h3>Broadcast announcement</h3><select name="event_id" required>@foreach($events as $event)<option value="{{ $event->id }}">{{ $event->title }}</option>@endforeach</select><textarea name="message" maxlength="300" placeholder="Announcement message" required></textarea><button>Send through Node.js</button></form></div></section>@endif @endauth
</main><footer>Laravel manages structure. Node.js powers real-time communication.</footer>
<script src="http://localhost:3000/socket.io/socket.io.js"></script><script>if(window.io){const socket=io('http://localhost:3000');socket.on('connect',()=>document.querySelector('#connection').textContent='● Socket connected');socket.on('new-announcement',data=>{document.querySelector('#live-message').textContent=data.message;document.querySelector('#connection').textContent='Received just now without refresh';});}else{document.querySelector('#connection').textContent='Start the Node.js server for live updates';}</script></body></html>
